name: tekartik_test_menu_flutter_repo
description: test_menu_flutter repo
version: 0.1.0
homepage: https://github.com/tekartik/sqflite
author: alex <alex@tekartik.com>
publish_to: none

environment:
  sdk: '>=2.4.0-dev <3.0.0'

dev_dependencies:
  pedantic: '>=1.4.0 <3.0.0'
  tekartik_travis_ci_flutter:
    git:
      url: git://github.com/tekartik/travis_ci_flutter.dart
      ref: dart2
    version: '>=0.1.0'
  process_run: '>=0.10.0'
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
    version: '>=0.7.1'
  test:

dependency_overrides:
  pedantic: '>=1.4.0 <3.0.0'

